//$Id: TPZPlasticStepID.h,v 1.3 2010-06-11 22:12:14 diogo Exp $

#ifndef TPZPLASTICSTEPID_H
#define TPZPLASTICSTEPID_H

const int LADEKIMPLASTICMODEL_ID                = 0;
const int SANDLERDIMAGGIOPLASTICMODEL_ID        = 1;
const int TPZDRUCKERPRAGERPLASTICMODEL_ID       = 2;
const int TPZMOHRCOULOMBPLASTICMODEL_ID         = 3;
const int TPZMODIFIEDMOHRCOULOMBPLASTICMODEL_ID = 4;
const int TPZWILLAMWARNKEPARENT_ID              = 5;
const int TPZVONMISES_ID                        = 6;
const int SANDLERDIMAGGIOPLASTICMODELL_ID       = 7;
const int SANDLERDIMAGGIOPLASTICMODELL2_ID      = 8;
const int SANDLERDIMAGGIOPLASTICMODELPV_ID      = 9;
const int MOHRCOULOMBPLASTICMODELPV_ID          = 10;

const int ELASTICMODEL_ID                       = 11;



const int BASEPLASTICMODEL_ID = 399;

const int TPZLADEKIM_ID             = BASEPLASTICMODEL_ID - LADEKIMPLASTICMODEL_ID;                // 399
const int TPZSANDLERDIMAGGIO_ID     = BASEPLASTICMODEL_ID - SANDLERDIMAGGIOPLASTICMODEL_ID;        // 398
const int TPZSANDLERDIMAGGIOL_ID    = BASEPLASTICMODEL_ID - SANDLERDIMAGGIOPLASTICMODELL_ID;       // 392
const int TPZSANDLERDIMAGGIOL2_ID   = BASEPLASTICMODEL_ID - SANDLERDIMAGGIOPLASTICMODELL2_ID;      // 391
const int TPZDRUCKERPRAGER_ID       = BASEPLASTICMODEL_ID - TPZDRUCKERPRAGERPLASTICMODEL_ID;       // 397
const int TPZMOHRCOULOMB_ID         = BASEPLASTICMODEL_ID - TPZMOHRCOULOMBPLASTICMODEL_ID;         // 396
const int TPZMODIFIEDMOHRCOULOMB_ID = BASEPLASTICMODEL_ID - TPZMODIFIEDMOHRCOULOMBPLASTICMODEL_ID; // 395
const int TPZSANDLERDIMAGGIOPV_ID   = BASEPLASTICMODEL_ID - SANDLERDIMAGGIOPLASTICMODELPV_ID;      // 390
const int TPZMOHRCOULOMBPV_ID       = BASEPLASTICMODEL_ID - MOHRCOULOMBPLASTICMODELPV_ID;          // 389
const int TPZELASTICPV_ID           = BASEPLASTICMODEL_ID - ELASTICMODEL_ID;                       // 388

const int LASTPLASTIC_ID            = MOHRCOULOMBPLASTICMODELPV_ID;                                // 10
//const int TPZMatElastoPlastic2D_ID;

#endif
